"""Add Don table

Revision ID: fe2ce343ca1f
Revises: 73aa33af31df
Create Date: 2024-05-21 17:17:31.478743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2ce343ca1f'
down_revision = '73aa33af31df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('don',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('montant', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=255), nullable=False),
    sa.Column('moyen_paiement', sa.String(length=255), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('don')
    # ### end Alembic commands ###
